server:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s

routes:
  - id: auth_service
    path: /api/v1/auth
    methods: ["POST"]
    backends:
      - url: "http://localhost:8081"
    middlewares: ["logging"]
    rate_limit:
      enabled: true
      rate: 0.2      
      capacity: 5   
    circuit_breaker:
      enabled: true
      max_requests: 1
      interval: 10
      timeout: 15
  - id: user_service
    path: /api/v1/users
    methods: ["GET", "POST"]
    backends:
      - url: "http://localhost:8082"
    middlewares: ["logging", "jwt"]
    rate_limit:
      enabled: true
      rate: 1      
      capacity: 2
    circuit_breaker:
      enabled: true
      max_requests: 1
      interval: 10
      timeout: 15